sudo: required
services:
  - docker
before_install:
  - docker build -t dibyajyoti/react-docker-basic -f Dockerfile.dev .

script:
  - docker run dibyajyoti/react-docker-basic npm run test -- --coverage
