version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
  react-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/app
    command: ["npm", "test"]
